### ISSUE TITLE
Consider dropping PyICU depencency

### ISSUE THREAD

**Issue by brechtm** [fellowinsights/prosemirror-py#61]
PyICU is a bit of an annoying dependency since it has no binary wheels available and thus requires the ICU dev package installed. Especially since Python comes with quite capable unicode capabilities built in.

I see that prosemirror-py is only using PyICU to determine the length of a unicode string. I guess this is because prosemirror doesn't count code points but code units (see [UnicodeString.length()](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1UnicodeString.html#a6d589423c64a498dbbbf7cd6d5fa995a)). This may be a [strange choice](https://stackoverflow.com/a/30775818/438249), so perhaps it makes sense to request changing this in prosemirror? I think it just uses Javascript's [string length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length) property.

In order to remove the need for PyICU, we can count the code units in pure Python. Since UnicodeString uses UTF-16 internally, the following code should be equivalent to the current implementation:

```python
len(u.encode('utf-16-le')) // 2
```

What do you think?

P.S Many thanks for this port! This is so much better than trying to get things to work using js2py.

**Comment by brechtm** [comment]
I have provideded a PR here: #62. This hasn't been tested properly yet.

**Comment by sciyoshi** [comment]
Thanks @brechtm for the contribution! It seems to me that you are correct, PyICU of course provides other functionality but we only use it for counting code units to match Javascript's behavior. I don't think upstream prosemirror will be able to change that since it relies on the JS runtime for its string manipulation, but the code you suggested should be equivalent.

We will try out the change from your PR on our end, but this looks like a great improvement.
